version: '3'

services:
  symfony:
    container_name: symfony
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - '8001:80'

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: intvw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    links:
      - mysql:mysql
    ports:
      - '8002:80'
    environment:
      PMA_HOST: mysql
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: rootpass

